[package]
name = "tent"
description = "A lightweight XML template engine"
license = "MIT"
version = "0.0.3"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[dependencies.tent_proc_macros]
path = "./proc_macros"
version = "0"

[workspace]
members = [".", "proc_macros"]

[dev-dependencies]
failure = "0.1"
