[package]
name = "tent_codegen"
description = "Procedure macros for tent"
license = "AGPL-3.0"
version = "0.0.11"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
