[package]
name = "tent_proc_macros"
description = "Procedure macros for tent"
license = "AGPL-3.0"
version = "0.0.1"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"